# Generated by Django 5.2.7 on 2025-10-29 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComandoTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_original', models.TextField()),
                ('texto_procesado', models.TextField(blank=True, null=True)),
                ('tipo_comando', models.CharField(choices=[('reporte', 'Generar Reporte'), ('busqueda', 'Búsqueda'), ('navegacion', 'Navegación'), ('accion', 'Acción del Sistema')], max_length=50)),
                ('contexto_aplicacion', models.CharField(choices=[('reports', 'Reportes'), ('products', 'Productos'), ('orders', 'Pedidos'), ('dashboard', 'Dashboard')], max_length=100)),
                ('intencion_detectada', models.CharField(blank=True, max_length=100, null=True)),
                ('parametros_extraidos', models.JSONField(blank=True, null=True)),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('exito', models.BooleanField(default=True)),
                ('respuesta_sistema', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comandos_texto',
            },
        ),
        migrations.CreateModel(
            name='ComandoVoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_original', models.TextField()),
                ('transcript_procesado', models.TextField(blank=True, null=True)),
                ('tipo_comando', models.CharField(choices=[('reporte', 'Generar Reporte'), ('busqueda', 'Búsqueda'), ('navegacion', 'Navegación'), ('accion', 'Acción del Sistema')], max_length=50)),
                ('contexto_aplicacion', models.CharField(choices=[('reports', 'Reportes'), ('products', 'Productos'), ('orders', 'Pedidos'), ('dashboard', 'Dashboard')], max_length=100)),
                ('intencion_detectada', models.CharField(blank=True, max_length=100, null=True)),
                ('parametros_extraidos', models.JSONField(blank=True, null=True)),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('duracion_procesamiento', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('exito', models.BooleanField(default=True)),
                ('respuesta_sistema', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comandos_voz',
            },
        ),
    ]
