# Generated by Django 4.2.7 on 2025-11-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(related_name='roles', through='users.RolPermiso', to='users.permiso'),
        ),
    ]
