# Generated by Django 4.2.7 on 2025-11-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rol_permisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='documento_identidad',
            field=models.CharField(blank=True, help_text='Ej: CI en Bolivia, DNI en Argentina, Cédula en Colombia', max_length=30, null=True),
        ),
    ]
