# Generated by Django 5.2.7 on 2025-10-29 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'db_table': 'configuracion_sistema',
            },
        ),
        migrations.CreateModel(
            name='BitacoraSistema',
            fields=[
                ('id_bitacora', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido'), ('advertencia', 'Advertencia')], default='exitoso', max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitácora del Sistema',
                'verbose_name_plural': 'Bitácoras del Sistema',
                'db_table': 'bitacora_sistema',
                'ordering': ['-fecha_accion'],
            },
        ),
    ]
