# Generated by Django 5.2.7 on 2025-10-29 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voice_commands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comando', models.CharField(blank=True, choices=[('voice', 'Voz'), ('text', 'Texto')], max_length=50, null=True)),
                ('tipo_reporte', models.CharField(choices=[('ventas', 'Ventas'), ('clientes', 'Clientes'), ('productos', 'Productos'), ('inventario', 'Inventario')], max_length=50)),
                ('formato_salida', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], max_length=20)),
                ('parametros', models.JSONField(blank=True, null=True)),
                ('consulta_sql', models.TextField(blank=True, null=True)),
                ('url_descarga', models.URLField(blank=True, max_length=500, null=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('comando_texto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voice_commands.comandotexto')),
                ('comando_voz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voice_commands.comandovoz')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reportes_generados',
            },
        ),
    ]
