# Generated by Django 5.2.7 on 2025-10-29 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modelo', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('ruta_modelo', models.CharField(blank=True, max_length=512, null=True)),
                ('fecha_entrenamiento', models.DateTimeField(blank=True, null=True)),
                ('parametros', models.JSONField(blank=True, null=True)),
                ('estado', models.CharField(default='entrenado', max_length=50)),
                ('precision', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modelos_ia',
            },
        ),
        migrations.CreateModel(
            name='PrediccionVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('resultado_prediccion', models.JSONField()),
                ('metricas', models.JSONField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.categoria')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_models.modeloia')),
            ],
            options={
                'db_table': 'predicciones_ventas',
            },
        ),
    ]
