# Generated by Django 4.2.7 on 2025-11-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('tarjeta_credito', 'Tarjeta de Crédito'), ('tarjeta_debito', 'Tarjeta de Débito')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='stripe_payment_intent_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
