# Generated by Django 4.2.7 on 2025-11-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pago_stripe_checkout_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
