# Generated by Django 4.2.7 on 2025-11-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_pago_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('card', 'Tarjeta'), ('qr', 'QR')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='moneda',
            field=models.CharField(default='BOB', max_length=3),
        ),
    ]
