# Generated by Django 4.2.7 on 2025-11-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_pago_metodo_pago_alter_pago_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='numero_seguimiento',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
