# Generated by Django 5.2.7 on 2025-11-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
