# Generated by Django 4.2.7 on 2025-11-09 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_marca_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='ubicacion_almacen',
        ),
    ]
