# Generated by Django 4.2.7 on 2025-11-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_producto_alto_producto_ancho_producto_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=models.SlugField(default='temporal', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
