# Generated by Django 4.2.7 on 2025-11-17 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_producto_fecha_actualizacion_alter_producto_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías de Envío',
                'db_table': 'categorias_envio',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.categoriaenvio'),
        ),
    ]
